name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We use a PAT instead

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/original-repo-owner/original-repo.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Sync with upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.AUNGOO}}
